version: "3.4"
services:
  app:
    restart: always
    build:
      context: ./app
    volumes:
      - ./app:/usr/src/app:rw
  nats:
    restart: always
    image: "nats:1.4.1"
    entrypoint: "/gnatsd -p 4222"
  emitter:
    restart: always
    build:
      context: ./emitter
    volumes:
      - ./emitter:/usr/src/app:rw